export const WHATSAPP_NUMBER = "6282149919150"; // TODO: ganti dengan nomor WhatsApp Queena
export const EMAIL = "noxjms@gmail.com";
export const LINKEDIN = "https://www.linkedin.com/in/queena-marella-9933892b5/";
export const LOCATION = "Malang, East Java, Indonesia";
// Kosong / tidak diset -> same-origin "/api" (mis. saat deploy di Vercel).
export const API_URL = `${process.env.REACT_APP_BACKEND_URL || ""}/api`;

export const NAV_IDS = ["home", "about", "experience", "global", "skills", "portfolio", "achievements", "contact"];

export const content = {
  en: {
    preloader: { tagline: "Bridging businesses across borders…" },
    nav: { home: "Home", about: "About", experience: "Experience", global: "Global", skills: "Skills", portfolio: "Portfolio", achievements: "Achievements", contact: "Contact" },
    hero: {
      greeting: "Hello, I'm",
      name: "Queena Marella",
      roles: ["International Business Communicator", "Professional Translation & Documentation", "Event Coordinator", "Cross-Cultural Collaborator"],
      sub: "Graduate in English for Business and Professional Communication from State Polytechnic of Malang, with a passion for international trade and global logistics.",
      badge: "Open to entry-level opportunities",
      viewWork: "View My Work",
      downloadCv: "Download CV",
      scroll: "Scroll to explore",
      portraitAlt: "Portrait of Queena Marella Leandra Sangalang in a navy blazer",
      portraitNote: "Professional portrait — coming soon",
      cards: [
        { icon: "grad", title: "Graduated 2026", sub: "State Polytechnic of Malang" },
        { icon: "globe", title: "IISMA 2024", sub: "UWA, Perth" },
        { icon: "star", title: "GPA 3.85 / 4.00", sub: "Highest Achievement Index ×2" },
      ],
    },
    marquee: ["International Trade", "Legal Translation", "Immigration Services", "Global Logistics", "Business Correspondence", "Cross-Cultural Communication"],
    about: {
      num: "01", title: "About Me", sub: "A bridge between languages, cultures, and businesses.",
      paragraphs: [
        "I'm a diligent, detail-oriented graduate of English for Business and Professional Communication from State Polytechnic of Malang (July 2026), with a keen interest in international trade, legal translation, immigration services, and global logistics.",
        "My studies in business correspondence, intercultural communication, translation, and public speaking gave me a solid foundation in cross-border documentation. I've built on it through an internship at PT Modern Mitra Sejati, a seafood distributor exporting to Japan, Malaysia, and Hong Kong, and through the IISMA exchange program at The University of Western Australia, where I learned to collaborate across cultures and communicate with clarity.",
        "Now, I'm looking to bring my skills to a professional environment and contribute to efficient international business operations.",
      ],
      infoTitle: "At a glance",
      info: [
        { k: "Name", v: "Queena Marella Leandra Sangalang" },
        { k: "Degree", v: "English for Business & Professional Communication" },
        { k: "University", v: "State Polytechnic of Malang (graduated July 2026)" },
        { k: "Location", v: "Malang, East Java, Indonesia" },
        { k: "Languages", v: "Indonesian (native), English (advanced — CEFR score to be confirmed)" },
      ],
      stats: [
        { value: 3.85, decimals: 2, label: "GPA (scale 4.00)" },
        { value: 13, suffix: "+", label: "Leadership & Project Roles" },
        { value: 4, label: "Awards" },
        { value: 2, label: "Professional Experiences" },
        { value: 1, label: "International Program (UWA, Perth)" },
      ],
      photoCaption: "Second portrait — MC duty or Perth moments",
      photoNote: "Photo coming soon",
    },
    education: {
      num: "02", title: "Education", sub: "A foundation in language, business, and culture.",
      items: [
        {
          school: "State Polytechnic of Malang", location: "Malang, East Java", period: "Aug 2022 – Jul 2026",
          degree: "English for Business and Professional Communication", extra: "GPA 3.85/4.00",
          bullets: [
            "Academic discussions, presentations, and group projects on international business, communication strategies, and professional writing.",
            "Hands-on practice in report writing, email drafting, and export-import & global workplace case studies.",
          ],
          tags: ["Business Correspondence", "Intercultural Communication", "Translation", "Public Speaking", "Report Writing", "Export-Import Case Studies"],
          note: "Official degree title on diploma to be confirmed (Diploma IV / Applied Bachelor).",
        },
        {
          school: "Republic Polytechnic, Singapore", location: "Singapore", period: "2023",
          degree: "Short Course — Communication in the Global Workplace", extra: "",
          bullets: [], tags: [],
        },
        {
          school: "SMAS Katolik Cor Jesu Malang", location: "Malang", period: "Jun 2019 – May 2021",
          degree: "Language and Culture", extra: "",
          bullets: [
            "4th Place, Citywide Dancesport Competition 2020",
            "13th Place, Java Island Dancesport Competition 2020",
            "Participant, Short Story Writing Competition — Ma Chung English Week 2021",
          ],
          tags: [],
        },
      ],
    },
    experience: {
      num: "03", title: "Work Experience", sub: "Where communication meets commerce.",
      pendingNote: "Details being finalized",
      items: [
        {
          company: "PT Modern Mitra Sejati", location: "Surabaya", role: "Internship", period: "Jul 2025 – Nov 2025", featured: true,
          desc: "Frozen seafood distributor (fish and shrimp) serving domestic and export markets — Japan, Malaysia, and Hong Kong — supported by modern cold storage facilities.",
          tasks: ["Export documentation & cross-border correspondence", "Communication with international buyers & logistics partners", "Measurable results & contribution"],
        },
        {
          company: "PT Jaxer Group Indonesia", location: "Jakarta", role: "Job title to be confirmed", period: "Freelance · Nov 2025 – Jun 2026", featured: false,
          desc: "ICT company focused on IT hardware production and digital education system development.",
          tasks: ["Role scope & responsibilities", "Key projects handled", "Results & contribution"],
        },
        {
          company: "CV Active Mitra Abadi", location: "", role: "Pilates Instructor", period: "17 Jul 2026 – Present", featured: false,
          desc: "Teaching Pilates sessions with a focus on posture, core strength, and safe, corrective movement.",
          tasks: [],
        },
      ],
    },
    global: {
      num: "04", title: "Global Experience", sub: "IISMA 2024 at The University of Western Australia.",
      from: "Malang, ID", to: "Perth, AU",
      mapCaption: "8,000+ km of growth — one exchange year that changed everything.",
      volunteeringTitle: "Volunteering in Perth",
      programs: [
        { program: "IISMA Vocational 2024", period: "Mar – Dec 2024", role: "Student Representative (Vocational)", points: ["Liaison between IISMA students and program coordinators", "Supported student welfare and adaptation", "Represented the cohort in official meetings"] },
        { program: "Industrial Exposure", period: "Oct – Nov 2024", role: "Public Relations Intern", points: ["Liaison between UWA and internship coordinators", "Email correspondence & merchandise coordination", "Front desk at Our Career Ready Sundowner"] },
        { program: "Culturise Challenge", period: "Aug – Sep 2024", role: "Event & Exhibition Division", points: ["Designed a traditional Indonesian culinary exhibition booth", "Coordinated traditional dance performances"] },
        { program: "IISMA Social Campaign: Zero Hunger", period: "May – Jun 2024", role: "Media & Communications Team Member", points: ["Produced digital communication materials & visual content", "Coordinated with media partners"] },
        { program: "Indonesia Future Development Project", period: "Oct – Nov 2024", role: "Essay Writer & Editor", points: ["Wrote a bilingual essay on the digital divide and e-commerce", "Edited in both English and Indonesian"] },
      ],
      volunteering: [
        { title: "Perth Running Festival", loc: "Optus Stadium, Perth", year: "2024" },
        { title: "UWA Booksale", loc: "Save the Children Australia", year: "2024" },
      ],
    },
    org: {
      num: "05", title: "Organizational Experience", sub: "Leading teams, running events, getting things done.",
      tabs: [
        { id: "esa", label: "English Student Association" },
        { id: "kmk", label: "Keluarga Mahasiswa Katolik" },
        { id: "events", label: "Event Highlights" },
      ],
      esaTitle: "English Student Association, State Polytechnic of Malang",
      esa: [
        { title: "Secretary — Research & Development Division", period: "2024/2025", desc: "Developed strategic work plans together with the division head and managed division administration." },
        { title: "Internal Division", period: "Aug 2023 – Jul 2024", desc: "Supervised planning, execution, and evaluation of internal programs; mentored members and reported to the Executive Board." },
        { title: "Event Coordinator", period: "2022 – 2023", desc: "Freshmen Gathering 2023, Open Recruitment 2023, Night Gathering & English Sport Competition 2022." },
      ],
      kmkTitle: "Keluarga Mahasiswa Katolik, State Polytechnic of Malang (Oct 2022 – Mar 2025)",
      kmk: [
        { title: "Household Division Member & Event Coordinator", period: "2023/2024 & 2024/2025", desc: "Event logistics, equipment procurement, and participant registration." },
        { title: "Field Coordinator — Basic Leadership Training 2025", period: "Jan – Mar 2025", desc: "Led planning and execution of the 2024/2025 → 2025/2026 handover ceremony; coordinated rundown and technical needs; oversaw day-of logistics." },
      ],
      eventsTitle: "Events I've Led",
      events: [
        { event: "Night Gathering & English Sport Competition 2023", role: "Chief Committee", note: "Developed the concept for both events and coordinated with division coordinators." },
        { event: "Night Gathering & English Sport Competition 2022", role: "Event Coordinator" },
        { event: "Lecturer–Student Dialogue 2024", role: "Treasurer" },
        { event: "Expo & Admission of New Students 2023", role: "Executive Secretary" },
        { event: "English Department Freshmen Gathering 2023", role: "Master of Ceremony" },
        { event: "Basic Leadership Training 2025", role: "Field Coordinator" },
        { event: "Mentoring Program 2024 & Easter Celebration 2023", role: "Event Coordinator" },
      ],
    },
    skills: {
      num: "06", title: "Skills", sub: "The toolkit behind the communication.",
      langTitle: "Language Skills", profTitle: "Professional Skills", softTitle: "Soft Skills", toolsTitle: "Tools",
      languages: [
        { name: "English", pct: 90, note: "Advanced — CEFR / TOEFL score to be confirmed", aspects: ["Speaking", "Writing", "Listening", "Reading"] },
        { name: "Indonesian", pct: 100, note: "Native", aspects: [] },
      ],
      professional: [
        { icon: "briefcase", label: "Business Communication" },
        { icon: "languages", label: "Legal / Professional Translation & Documentation" },
        { icon: "pen", label: "Report Writing & Policy Drafting" },
        { icon: "mic", label: "Public Speaking & Moderation" },
        { icon: "calendar", label: "Event Planning & Coordination" },
        { icon: "clipboard", label: "Administrative Management" },
        { icon: "boxes", label: "Inventory & Logistics Management" },
      ],
      soft: ["Leadership", "Team Collaboration", "Cross-Cultural Communication", "Problem-Solving", "Time Management", "Initiative & Responsibility", "Adaptability"],
      tools: ["Microsoft Office Suite", "Google Workspace", "Canva", "CapCut", "Zoom / Teams"],
    },
    portfolio: {
      num: "07", title: "Portfolio", sub: "Selected works across writing, business, media, and events.",
      filters: [
        { id: "all", label: "All" },
        { id: "writing", label: "Writing & Translation" },
        { id: "business", label: "Business Documents" },
        { id: "media", label: "Media & Campaign" },
        { id: "events", label: "Events & Leadership" },
      ],
      viewDetails: "View Details",
      closeLabel: "Close",
      modalLabels: { background: "Background", role: "My Role", outcome: "Outcome", deliverable: "Deliverable" },
      pending: "File being prepared — available on request",
      items: [
        { id: "essay", cat: "writing", title: "Bridging the Gap: Addressing Indonesia's Digital Divide through E-Commerce", desc: "Bilingual essay for the Indonesia Future Development Project.", background: "Written during the IISMA program at UWA to explore how e-commerce can close Indonesia's digital divide.", role: "Researcher, writer, and editor — in both English and Indonesian.", outcome: "A polished bilingual essay submitted for the Indonesia Future Development Project (Oct–Nov 2024)." },
        { id: "translation", cat: "writing", title: "EN–ID / ID–EN Translation Samples", desc: "Selected coursework translations, anonymized.", background: "Translation coursework from the English for Business & Professional Communication program.", role: "Translator and self-editor.", outcome: "Accurate, register-appropriate translations across business and legal-style texts." },
        { id: "correspondence", cat: "business", title: "Business Email, Formal Letter & Report Pack", desc: "Coursework samples of professional business writing.", background: "Business correspondence practice: emails, formal letters, and structured reports.", role: "Writer.", outcome: "A complete pack demonstrating professional tone, structure, and clarity." },
        { id: "bizplan", cat: "business", title: "2nd Best Business Plan Idea (2022)", desc: "Awarded by the Pre-Study Department of Business Administration.", background: "A business plan competition held by the Pre-Study Department of Business Administration.", role: "Ideation and pitching.", outcome: "2nd Best Business Plan Idea, 2022." },
        { id: "internship", cat: "business", title: "Internship Report — PT Modern Mitra Sejati", desc: "Non-confidential version of the export-industry internship report.", background: "Final report from a 5-month internship at a frozen seafood exporter serving Japan, Malaysia, and Hong Kong.", role: "Intern — documentation and correspondence support.", outcome: "A structured report covering operations, export flow, and cold-storage logistics (non-confidential version)." },
        { id: "zerohunger", cat: "media", title: "IISMA Social Campaign: Zero Hunger", desc: "Digital communication materials and visual content.", background: "An IISMA social campaign raising awareness for Zero Hunger (May–Jun 2024).", role: "Media & Communications team member.", outcome: "Published digital campaign content coordinated with media partners." },
        { id: "tiktok", cat: "media", title: "TikTok Video — Arrayan Executive Village", desc: "Most Creative Promotion, Batu (2023).", background: "A promotional video competition for Arrayan Executive Village, Batu.", role: "Creative concept and production.", outcome: "Won Most Creative Promotion, 2023." },
        { id: "nightgathering", cat: "events", title: "Night Gathering & English Sport Competition", desc: "Concept, rundown, and documentation of the annual event.", background: "The English Department's annual flagship event, led in 2022 and 2023.", role: "Chief Committee (2023) — developed the concept for both events and coordinated division coordinators.", outcome: "Successfully delivered two editions with full rundown and cross-division coordination." },
        { id: "mcbooth", cat: "events", title: "MC Freshmen Gathering & Culturise Exhibition Booth", desc: "Stage moderation and exhibition design highlights.", background: "MC duty at the Freshmen Gathering 2023 and exhibition design for UWA's Culturise Challenge.", role: "Master of Ceremony; Event & Exhibition division member.", outcome: "Smooth live moderation and a well-received Indonesian culinary booth in Perth." },
      ],
    },
    achievements: {
      num: "08", title: "Achievements & Certificates", sub: "Recognition along the way.",
      volunteeringTitle: "Volunteering",
      items: [
        { title: "Student with Highest Achievement Index", issuer: "State Polytechnic of Malang", year: "Odd Semester 2023/2024" },
        { title: "Student with Highest Achievement Index", issuer: "State Polytechnic of Malang", year: "Odd Semester 2022/2023" },
        { title: "Most Creative Promotion — TikTok Video Competition", issuer: "Arrayan Executive Village, Batu", year: "2023" },
        { title: "2nd Best Business Plan Idea", issuer: "Pre-Study Department of Business Administration", year: "2022" },
        { title: "IISMA Webinar with Edupact", issuer: "Webinar Participant", year: "20 January 2024" },
        { title: "Workshop — Stronger Spine & Better Posture: Relieve Neck & Back Pain Through Pilates", issuer: "Daniel Choi · Pilates Instructor at Active by FeelFit, FeelFit Journey", year: "29 November 2025" },
        { title: "Workshop — Corrective Pilates Masterclass", issuer: "Daniel Choi · Pilates Instructor at Active by FeelFit, FeelFit Journey", year: "25 April 2026" },
      ],
      volunteering: [
        { title: "Universal Open 2026 International Billiard Tournament", year: "Jakarta · 25–28 Jun 2026" },
        { title: "Panti Asuhan Darul Jundi", year: "2025" },
        { title: "Perth Running Festival", year: "2024" },
        { title: "UWA Booksale — Save the Children Australia", year: "2024" },
      ],
    },
    contact: {
      num: "09", title: "Let's build bridges together.",
      sub: "Open to entry-level roles in international trade, legal translation, immigration services, and global logistics — or simply a good conversation.",
      whatsappTitle: "Chat on WhatsApp",
      whatsappSub: "The fastest way to reach me — usually replies within a day.",
      quickLabel: "Write a quick message (optional)",
      quickPlaceholder: "Hi Queena, I saw your portfolio and…",
      send: "Open WhatsApp",
      emailLabel: "Email",
      linkedinLabel: "LinkedIn",
      locationLabel: "Location",
    },
    footer: {
      tagline: "Bridging businesses across borders through clear, professional communication.",
      explore: "Explore", connect: "Connect",
      rights: "© 2026 Queena Marella Leandra Sangalang. Crafted with care.",
      backTop: "Back to top",
    },
  },

  id: {
    preloader: { tagline: "Menjembatani bisnis lintas negara…" },
    nav: { home: "Beranda", about: "Tentang", experience: "Pengalaman", global: "Global", skills: "Keahlian", portfolio: "Portofolio", achievements: "Prestasi", contact: "Kontak" },
    hero: {
      greeting: "Halo, saya",
      name: "Queena Marella",
      roles: ["Komunikator Bisnis Internasional", "Penerjemahan & Dokumentasi Profesional", "Koordinator Acara", "Kolaborator Lintas Budaya"],
      sub: "Lulusan Bahasa Inggris untuk Komunikasi Bisnis dan Profesional dari Politeknik Negeri Malang, dengan minat pada perdagangan internasional dan logistik global.",
      badge: "Terbuka untuk peluang entry-level",
      viewWork: "Lihat Karya Saya",
      downloadCv: "Unduh CV",
      scroll: "Gulir untuk menjelajah",
      portraitAlt: "Potret Queena Marella Leandra Sangalang dengan blazer navy",
      portraitNote: "Foto profesional — segera hadir",
      cards: [
        { icon: "grad", title: "Lulus 2026", sub: "Politeknik Negeri Malang" },
        { icon: "globe", title: "IISMA 2024", sub: "UWA, Perth" },
        { icon: "star", title: "IPK 3,85 / 4,00", sub: "Indeks Prestasi Tertinggi ×2" },
      ],
    },
    marquee: ["Perdagangan Internasional", "Penerjemahan Hukum", "Layanan Keimigrasian", "Logistik Global", "Korespondensi Bisnis", "Komunikasi Lintas Budaya"],
    about: {
      num: "01", title: "Tentang Saya", sub: "Jembatan antara bahasa, budaya, dan bisnis.",
      paragraphs: [
        "Saya lulusan Bahasa Inggris untuk Komunikasi Bisnis dan Profesional dari Politeknik Negeri Malang (Juli 2026) yang tekun dan detail-oriented, dengan minat kuat pada perdagangan internasional, penerjemahan hukum, layanan keimigrasian, dan logistik global.",
        "Perkuliahan saya di bidang korespondensi bisnis, komunikasi antarbudaya, penerjemahan, dan public speaking menjadi fondasi kuat dalam dokumentasi lintas negara. Fondasi itu saya perkuat melalui magang di PT Modern Mitra Sejati — distributor seafood yang mengekspor ke Jepang, Malaysia, dan Hong Kong — serta program IISMA di The University of Western Australia, tempat saya belajar berkolaborasi lintas budaya dan berkomunikasi dengan jernih.",
        "Kini, saya siap membawa kemampuan tersebut ke lingkungan profesional dan berkontribusi pada operasi bisnis internasional yang efisien.",
      ],
      infoTitle: "Sekilas tentang saya",
      info: [
        { k: "Nama", v: "Queena Marella Leandra Sangalang" },
        { k: "Program Studi", v: "Bahasa Inggris untuk Komunikasi Bisnis & Profesional" },
        { k: "Universitas", v: "Politeknik Negeri Malang (lulus Juli 2026)" },
        { k: "Domisili", v: "Malang, Jawa Timur, Indonesia" },
        { k: "Bahasa", v: "Indonesia (native), Inggris (mahir — skor CEFR menyusul)" },
      ],
      stats: [
        { value: 3.85, decimals: 2, label: "IPK (skala 4,00)" },
        { value: 13, suffix: "+", label: "Peran Kepemimpinan & Proyek" },
        { value: 4, label: "Penghargaan" },
        { value: 2, label: "Pengalaman Profesional" },
        { value: 1, label: "Program Internasional (UWA, Perth)" },
      ],
      photoCaption: "Potret kedua — saat MC atau momen di Perth",
      photoNote: "Foto segera hadir",
    },
    education: {
      num: "02", title: "Pendidikan", sub: "Fondasi di bidang bahasa, bisnis, dan budaya.",
      items: [
        {
          school: "Politeknik Negeri Malang", location: "Malang, Jawa Timur", period: "Agu 2022 – Jul 2026",
          degree: "Bahasa Inggris untuk Komunikasi Bisnis dan Profesional", extra: "IPK 3,85/4,00",
          bullets: [
            "Diskusi akademik, presentasi, dan proyek kelompok seputar bisnis internasional, strategi komunikasi, dan penulisan profesional.",
            "Praktik report writing, email drafting, serta studi kasus ekspor-impor dan global workplace.",
          ],
          tags: ["Korespondensi Bisnis", "Komunikasi Antarbudaya", "Penerjemahan", "Public Speaking", "Report Writing", "Studi Kasus Ekspor-Impor"],
          note: "Nama gelar resmi di ijazah akan dikonfirmasi (Diploma IV / Sarjana Terapan).",
        },
        {
          school: "Republic Polytechnic, Singapura", location: "Singapura", period: "2023",
          degree: "Short Course — Communication in the Global Workplace", extra: "",
          bullets: [], tags: [],
        },
        {
          school: "SMAS Katolik Cor Jesu Malang", location: "Malang", period: "Jun 2019 – Mei 2021",
          degree: "Bahasa dan Budaya", extra: "",
          bullets: [
            "Juara 4, Dancesport Competition tingkat kota 2020",
            "Peringkat 13, Dancesport Competition Pulau Jawa 2020",
            "Peserta, Lomba Menulis Cerpen — Ma Chung English Week 2021",
          ],
          tags: [],
        },
      ],
    },
    experience: {
      num: "03", title: "Pengalaman Kerja", sub: "Tempat komunikasi bertemu dengan perdagangan.",
      pendingNote: "Detail sedang disusun",
      items: [
        {
          company: "PT Modern Mitra Sejati", location: "Surabaya", role: "Magang", period: "Jul 2025 – Nov 2025", featured: true,
          desc: "Distributor frozen seafood (ikan dan udang) dengan pasar domestik dan ekspor ke Jepang, Malaysia, dan Hong Kong, didukung fasilitas cold storage modern.",
          tasks: ["Dokumentasi ekspor & korespondensi lintas negara", "Komunikasi dengan buyer internasional & mitra logistik", "Hasil dan kontribusi terukur"],
        },
        {
          company: "PT Jaxer Group Indonesia", location: "Jakarta", role: "Job title menyusul", period: "Freelance · Nov 2025 – Jun 2026", featured: false,
          desc: "Perusahaan ICT yang berfokus pada produksi IT hardware dan pengembangan sistem pendidikan digital.",
          tasks: ["Ruang lingkup & tanggung jawab", "Proyek utama yang ditangani", "Hasil & kontribusi"],
        },
        {
          company: "CV Active Mitra Abadi", location: "", role: "Instruktur Pilates", period: "17 Jul 2026 – Sekarang", featured: false,
          desc: "Mengajar sesi Pilates dengan fokus pada postur, kekuatan core, dan gerakan korektif yang aman.",
          tasks: [],
        },
      ],
    },
    global: {
      num: "04", title: "Pengalaman Global", sub: "IISMA 2024 di The University of Western Australia.",
      from: "Malang, ID", to: "Perth, AU",
      mapCaption: "8.000+ km perjalanan — satu tahun pertukaran yang mengubah segalanya.",
      volunteeringTitle: "Kegiatan Relawan di Perth",
      programs: [
        { program: "IISMA Vocational 2024", period: "Mar – Des 2024", role: "Student Representative (Vocational)", points: ["Penghubung mahasiswa IISMA dan koordinator program", "Mendukung kesejahteraan dan adaptasi mahasiswa", "Mewakili angkatan di rapat resmi"] },
        { program: "Industrial Exposure", period: "Okt – Nov 2024", role: "Public Relations Intern", points: ["Penghubung UWA dan koordinator magang", "Korespondensi email & koordinasi merchandise", "Front desk di Our Career Ready Sundowner"] },
        { program: "Culturise Challenge", period: "Agu – Sep 2024", role: "Divisi Event & Exhibition", points: ["Merancang booth pameran kuliner tradisional Indonesia", "Mengoordinasi pertunjukan tari tradisional"] },
        { program: "IISMA Social Campaign: Zero Hunger", period: "Mei – Jun 2024", role: "Media & Communications Team Member", points: ["Membuat materi komunikasi digital & konten visual", "Koordinasi dengan media partner"] },
        { program: "Indonesia Future Development Project", period: "Okt – Nov 2024", role: "Essay Writer & Editor", points: ["Menulis esai bilingual tentang digital divide dan e-commerce", "Editing dalam bahasa Inggris dan Indonesia"] },
      ],
      volunteering: [
        { title: "Perth Running Festival", loc: "Optus Stadium, Perth", year: "2024" },
        { title: "UWA Booksale", loc: "Save the Children Australia", year: "2024" },
      ],
    },
    org: {
      num: "05", title: "Pengalaman Organisasi", sub: "Memimpin tim, menjalankan acara, menyelesaikan pekerjaan.",
      tabs: [
        { id: "esa", label: "English Student Association" },
        { id: "kmk", label: "Keluarga Mahasiswa Katolik" },
        { id: "events", label: "Sorotan Acara" },
      ],
      esaTitle: "English Student Association, Politeknik Negeri Malang",
      esa: [
        { title: "Sekretaris — Divisi Research & Development", period: "2024/2025", desc: "Menyusun rencana kerja strategis bersama kepala divisi dan mengelola administrasi divisi." },
        { title: "Divisi Internal", period: "Agu 2023 – Jul 2024", desc: "Mengawasi perencanaan, pelaksanaan, dan evaluasi program internal; membimbing anggota dan melapor ke Executive Board." },
        { title: "Event Coordinator", period: "2022 – 2023", desc: "Freshmen Gathering 2023, Open Recruitment 2023, Night Gathering & English Sport Competition 2022." },
      ],
      kmkTitle: "Keluarga Mahasiswa Katolik, Politeknik Negeri Malang (Okt 2022 – Mar 2025)",
      kmk: [
        { title: "Anggota Divisi Household & Event Coordinator", period: "2023/2024 & 2024/2025", desc: "Logistik acara, pengadaan perlengkapan, dan registrasi peserta." },
        { title: "Field Coordinator — Basic Leadership Training 2025", period: "Jan – Mar 2025", desc: "Memimpin perencanaan dan pelaksanaan serah terima kepengurusan 2024/2025 ke 2025/2026; mengoordinasi rundown dan kebutuhan teknis; mengawasi logistik di hari acara." },
      ],
      eventsTitle: "Acara yang Saya Pimpin",
      events: [
        { event: "Night Gathering & English Sport Competition 2023", role: "Chief Committee", note: "Menyusun konsep kedua acara dan berkoordinasi dengan para koordinator divisi." },
        { event: "Night Gathering & English Sport Competition 2022", role: "Event Coordinator" },
        { event: "Lecturer–Student Dialogue 2024", role: "Treasurer" },
        { event: "Expo & Admission of New Students 2023", role: "Executive Secretary" },
        { event: "English Department Freshmen Gathering 2023", role: "Master of Ceremony" },
        { event: "Basic Leadership Training 2025", role: "Field Coordinator" },
        { event: "Mentoring Program 2024 & Easter Celebration 2023", role: "Event Coordinator" },
      ],
    },
    skills: {
      num: "06", title: "Keahlian", sub: "Perangkat di balik komunikasi yang baik.",
      langTitle: "Kemampuan Bahasa", profTitle: "Keahlian Profesional", softTitle: "Soft Skills", toolsTitle: "Tools",
      languages: [
        { name: "Bahasa Inggris", pct: 90, note: "Mahir — skor CEFR / TOEFL menyusul", aspects: ["Speaking", "Writing", "Listening", "Reading"] },
        { name: "Bahasa Indonesia", pct: 100, note: "Native", aspects: [] },
      ],
      professional: [
        { icon: "briefcase", label: "Komunikasi Bisnis" },
        { icon: "languages", label: "Penerjemahan & Dokumentasi Legal/Profesional" },
        { icon: "pen", label: "Report Writing & Penyusunan Kebijakan" },
        { icon: "mic", label: "Public Speaking & Moderasi" },
        { icon: "calendar", label: "Perencanaan & Koordinasi Acara" },
        { icon: "clipboard", label: "Manajemen Administrasi" },
        { icon: "boxes", label: "Manajemen Inventaris & Logistik" },
      ],
      soft: ["Kepemimpinan", "Kolaborasi Tim", "Komunikasi Lintas Budaya", "Pemecahan Masalah", "Manajemen Waktu", "Inisiatif & Tanggung Jawab", "Adaptabilitas"],
      tools: ["Microsoft Office Suite", "Google Workspace", "Canva", "CapCut", "Zoom / Teams"],
    },
    portfolio: {
      num: "07", title: "Portofolio", sub: "Karya pilihan di bidang penulisan, bisnis, media, dan acara.",
      filters: [
        { id: "all", label: "Semua" },
        { id: "writing", label: "Penulisan & Penerjemahan" },
        { id: "business", label: "Dokumen Bisnis" },
        { id: "media", label: "Media & Kampanye" },
        { id: "events", label: "Acara & Kepemimpinan" },
      ],
      viewDetails: "Lihat Detail",
      closeLabel: "Tutup",
      modalLabels: { background: "Latar Belakang", role: "Peran Saya", outcome: "Hasil", deliverable: "Berkas" },
      pending: "Berkas sedang disiapkan — tersedia atas permintaan",
      items: [
        { id: "essay", cat: "writing", title: "Bridging the Gap: Addressing Indonesia's Digital Divide through E-Commerce", desc: "Esai bilingual untuk Indonesia Future Development Project.", background: "Ditulis selama program IISMA di UWA untuk mengkaji peran e-commerce dalam menutup kesenjangan digital Indonesia.", role: "Peneliti, penulis, dan editor — dalam bahasa Inggris dan Indonesia.", outcome: "Esai bilingual yang rampung dan diserahkan untuk Indonesia Future Development Project (Okt–Nov 2024)." },
        { id: "translation", cat: "writing", title: "Sampel Terjemahan EN–ID / ID–EN", desc: "Kumpulan tugas penerjemahan, versi disamarkan.", background: "Tugas penerjemahan dari program studi Bahasa Inggris untuk Komunikasi Bisnis & Profesional.", role: "Penerjemah sekaligus self-editor.", outcome: "Terjemahan akurat dengan register yang tepat untuk teks bisnis dan legal." },
        { id: "correspondence", cat: "business", title: "Paket Email Bisnis, Surat Formal & Laporan", desc: "Sampel tugas penulisan bisnis profesional.", background: "Latihan korespondensi bisnis: email, surat formal, dan laporan terstruktur.", role: "Penulis.", outcome: "Paket lengkap yang menunjukkan nada profesional, struktur, dan kejernihan." },
        { id: "bizplan", cat: "business", title: "2nd Best Business Plan Idea (2022)", desc: "Penghargaan dari Pre-Study Department of Business Administration.", background: "Kompetisi business plan yang diselenggarakan Pre-Study Department of Business Administration.", role: "Ideasi dan pitching.", outcome: "Juara 2 Best Business Plan Idea, 2022." },
        { id: "internship", cat: "business", title: "Laporan Magang — PT Modern Mitra Sejati", desc: "Versi non-rahasia laporan magang industri ekspor.", background: "Laporan akhir magang 5 bulan di eksportir frozen seafood dengan pasar Jepang, Malaysia, dan Hong Kong.", role: "Intern — dukungan dokumentasi dan korespondensi.", outcome: "Laporan terstruktur tentang operasi, alur ekspor, dan logistik cold storage (versi non-rahasia)." },
        { id: "zerohunger", cat: "media", title: "IISMA Social Campaign: Zero Hunger", desc: "Materi komunikasi digital dan konten visual.", background: "Kampanye sosial IISMA untuk meningkatkan kesadaran Zero Hunger (Mei–Jun 2024).", role: "Anggota tim Media & Communications.", outcome: "Konten kampanye digital yang tayang dan terkoordinasi dengan media partner." },
        { id: "tiktok", cat: "media", title: "Video TikTok — Arrayan Executive Village", desc: "Most Creative Promotion, Batu (2023).", background: "Kompetisi video promosi untuk Arrayan Executive Village, Batu.", role: "Konsep kreatif dan produksi.", outcome: "Meraih Most Creative Promotion, 2023." },
        { id: "nightgathering", cat: "events", title: "Night Gathering & English Sport Competition", desc: "Konsep, rundown, dan dokumentasi acara tahunan.", background: "Acara tahunan unggulan English Department, dipimpin pada 2022 dan 2023.", role: "Chief Committee (2023) — menyusun konsep kedua acara dan mengoordinasi koordinator divisi.", outcome: "Dua edisi berjalan sukses dengan rundown lengkap dan koordinasi lintas divisi." },
        { id: "mcbooth", cat: "events", title: "MC Freshmen Gathering & Booth Culturise", desc: "Sorotan moderasi panggung dan desain pameran.", background: "Tugas MC di Freshmen Gathering 2023 dan desain booth untuk Culturise Challenge di UWA.", role: "Master of Ceremony; anggota divisi Event & Exhibition.", outcome: "Moderasi langsung yang lancar dan booth kuliner Indonesia yang diminati di Perth." },
      ],
    },
    achievements: {
      num: "08", title: "Prestasi & Sertifikat", sub: "Apresiasi di sepanjang perjalanan.",
      volunteeringTitle: "Kegiatan Relawan",
      items: [
        { title: "Student with Highest Achievement Index", issuer: "Politeknik Negeri Malang", year: "Semester Ganjil 2023/2024" },
        { title: "Student with Highest Achievement Index", issuer: "Politeknik Negeri Malang", year: "Semester Ganjil 2022/2023" },
        { title: "Most Creative Promotion — TikTok Video Competition", issuer: "Arrayan Executive Village, Batu", year: "2023" },
        { title: "2nd Best Business Plan Idea", issuer: "Pre-Study Department of Business Administration", year: "2022" },
        { title: "IISMA Webinar with Edupact", issuer: "Peserta Webinar", year: "20 Januari 2024" },
        { title: "Workshop — Stronger Spine & Better Posture: Relieve Neck & Back Pain Through Pilates", issuer: "Daniel Choi · Pilates Instructor at Active by FeelFit, FeelFit Journey", year: "29 November 2025" },
        { title: "Workshop — Corrective Pilates Masterclass", issuer: "Daniel Choi · Pilates Instructor at Active by FeelFit, FeelFit Journey", year: "25 April 2026" },
      ],
      volunteering: [
        { title: "Universal Open 2026 International Billiard Tournament", year: "Jakarta · 25–28 Jun 2026" },
        { title: "Panti Asuhan Darul Jundi", year: "2025" },
        { title: "Perth Running Festival", year: "2024" },
        { title: "UWA Booksale — Save the Children Australia", year: "2024" },
      ],
    },
    contact: {
      num: "09", title: "Mari membangun jembatan bersama.",
      sub: "Terbuka untuk peran entry-level di perdagangan internasional, penerjemahan hukum, layanan keimigrasian, dan logistik global — atau sekadar mengobrol santai.",
      whatsappTitle: "Chat via WhatsApp",
      whatsappSub: "Cara tercepat menghubungi saya — biasanya dibalas dalam sehari.",
      quickLabel: "Tulis pesan singkat (opsional)",
      quickPlaceholder: "Halo Queena, saya melihat portofoliomu dan…",
      send: "Buka WhatsApp",
      emailLabel: "Email",
      linkedinLabel: "LinkedIn",
      locationLabel: "Lokasi",
    },
    footer: {
      tagline: "Menjembatani bisnis lintas negara melalui komunikasi yang jernih dan profesional.",
      explore: "Jelajahi", connect: "Terhubung",
      rights: "© 2026 Queena Marella Leandra Sangalang. Dibuat dengan sepenuh hati.",
      backTop: "Kembali ke atas",
    },
  },
};
